name: Metrics
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_repositories_star: 0
          plugin_achievements: no
